// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQw5IAIZhZ28zjZejHwXTuvoYiuVPFjH8',
    appId: '1:352966371283:web:a3b69eead2fc0d10f1f126',
    messagingSenderId: '352966371283',
    projectId: 'live-score-app-cde2f',
    authDomain: 'live-score-app-cde2f.firebaseapp.com',
    storageBucket: 'live-score-app-cde2f.firebasestorage.app',
    measurementId: 'G-33Q9EGKRF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjzWPEeyun58zxMFfqWlLZKOepqOrNW0',
    appId: '1:352966371283:android:61c658b6e4d5abeef1f126',
    messagingSenderId: '352966371283',
    projectId: 'live-score-app-cde2f',
    storageBucket: 'live-score-app-cde2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpO6-XODlfnatHRPVyGXfswqRLzsM70a0',
    appId: '1:352966371283:ios:b719be87ac784fe7f1f126',
    messagingSenderId: '352966371283',
    projectId: 'live-score-app-cde2f',
    storageBucket: 'live-score-app-cde2f.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

}